sudo: required

services:
  - docker

script:
  - docker build -t weblate .
  - docker run --name weblate -e WEBLATE_DEBUG=True -e WEBLATE_ADMIN_NAME=john -e WEBLATE_ADMIN_EMAIL=john@example.com -e WEBLATE_EMAIL=john@example.com -d weblate
  - docker exec weblate /bin/sh -c "apt-get update && apt-get install curl -y --no-install-recommends && curl -f localhost:8000"
  - docker logs weblate
