#!/bin/bash

set -ea # Exit on Error and Export all vars

. ./conf.env

while ! nc -z $DB_HOST $DB_PORT; do
  echo "Waiting for Database at $DB_HOST:$DB_PORT..."
  sleep 2
done

# Allow migration to fail due to already initialized DB
{
   django-admin migrate --noinput &&
   django-admin collectstatic --noinput &&
   ./createAdminOnce.py
}

django-admin runserver 0.0.0.0:8000
